In [1]:
#Import pandas
import pandas as pd

In [5]:
#Create panda series using list
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [11]:
data = [10, 20, 30, 40, 'A']
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4     A
dtype: object


In [13]:
#Create series using a custom index
data = [1, 2, 3, 4]
i = ['A', 'B', 'C', 'D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [17]:
#Create series using dictionary
data = {'a': 10, 'b': 20, 'c': 30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [19]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [27]:
#Create series using numpy array
import numpy as np
data = np.array([100, 200, 300])
series = pd.Series(data, index=['a','b','c'])
print(series)

a    100
b    200
c    300
dtype: int32


In [29]:
import numpy as np
data = np.array([100, 200, 300])
series = pd.Series(data, index=[1, 2, 3])
print(series)

1    100
2    200
3    300
dtype: int32


In [31]:
#PANDAS DATAFRAME

In [45]:
#Create pandas dataframe from dictionary of lists
import pandas as pd
data = {'Name': ['Alice', 'Bob','Mary'], 'Age': [25, 30, 34],'Country':["USA","UK","AUS"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS


In [57]:
import pandas as pd
data = {'Name': ['Pallavi', 'Divya','Srushti', 'Shivani'], 'Age': [19, 19, 19, 19],'CGPA':[9.0,9.5,9.5,9.0], 'Subjects':['Maths','Social','Science','English']}
df = pd.DataFrame(data)
print(df)

      Name  Age  CGPA Subjects
0  Pallavi   19   9.0    Maths
1    Divya   19   9.5   Social
2  Srushti   19   9.5  Science
3  Shivani   19   9.0  English


In [53]:
#Create pandas dataframe from numpy array
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [59]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(array)
df = pd.DataFrame(array)
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
