#### Ways of creating Numpy

In [7]:
from numpy import*

In [19]:
arr = array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [17]:
arr = array([1,2,3,4,5])
print(arr.dtype)

int32


In [11]:
arr = array([1,2,3,4,5.0])
print(arr.dtype)

float64


In [21]:
arr = array([1,2,3,4,5.0])
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [23]:
arr = array([1,2,3,4,5.0],float)
print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [25]:
arr = linspace(0,16,10)
print(arr)

[ 0.          1.77777778  3.55555556  5.33333333  7.11111111  8.88888889
 10.66666667 12.44444444 14.22222222 16.        ]


In [29]:
arr = linspace(0,19,14)
print(arr)

[ 0.          1.46153846  2.92307692  4.38461538  5.84615385  7.30769231
  8.76923077 10.23076923 11.69230769 13.15384615 14.61538462 16.07692308
 17.53846154 19.        ]


In [31]:
arr = linspace(0,19)
print(arr)

[ 0.          0.3877551   0.7755102   1.16326531  1.55102041  1.93877551
  2.32653061  2.71428571  3.10204082  3.48979592  3.87755102  4.26530612
  4.65306122  5.04081633  5.42857143  5.81632653  6.20408163  6.59183673
  6.97959184  7.36734694  7.75510204  8.14285714  8.53061224  8.91836735
  9.30612245  9.69387755 10.08163265 10.46938776 10.85714286 11.24489796
 11.63265306 12.02040816 12.40816327 12.79591837 13.18367347 13.57142857
 13.95918367 14.34693878 14.73469388 15.12244898 15.51020408 15.89795918
 16.28571429 16.67346939 17.06122449 17.44897959 17.83673469 18.2244898
 18.6122449  19.        ]


In [33]:
arr = arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [37]:
arr = logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [41]:
arr = logspace(1,40,5)
print('%.2f' %arr[4])

10000000000000000303786028427003666890752.00


In [43]:
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [59]:
arr = ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [47]:
arr = ones(5,int)
print(arr)

[1 1 1 1 1]


#### Coping,adding,Aalising an Array

In [62]:
arr = array([1,2,3,4,5])
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [66]:
arr1 = array([1,2,3,4,5])
arr2 = array([5,6,2,1,3])
arr3 = arr1 + arr2
print(arr3)

[6 8 5 5 8]


In [80]:
arr1 = array([1,2,3,4,5])


print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [78]:
arr1 = array([1,2,3,4,5])


print(cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [76]:
arr1 = array([1,2,3,4,5])


print(log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [82]:
arr1 = array([1,2,3,4,5])


print(sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [84]:
arr1 = array([1,2,3,4,5])


print(sum(arr1))

15


In [86]:
arr1 = array([1,2,3,4,5])


print(min(arr1))

1


In [88]:
arr1 = array([1,2,3,4,5])


print(max(arr1))

5


In [92]:
arr1 = array([1,2,3,4,5])
arr2 = array([5,6,2,1,3])

print(concatenate([arr1,arr2]))

[1 2 3 4 5 5 6 2 1 3]


In [94]:
arr1 = array([2,4,5,6,7])
arr2 = arr1
print(arr1)
print(arr2)

[2 4 5 6 7]
[2 4 5 6 7]


In [96]:
arr1 = array([2,4,5,6,7])
arr2 = arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 4 5 6 7]
[2 4 5 6 7]
1568385559376
1568385559376


In [98]:
arr1 = array([2,4,5,6,7])
arr2 = arr1.view()
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 4 5 6 7]
[2 4 5 6 7]
1568385562448
1568385564560


In [100]:
arr1 = array([2,4,5,6,7])
arr2 = arr1.copy()
arr1[1] = 9
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 9 5 6 7]
[2 4 5 6 7]
1568385559472
1568387414608


In [102]:
arr1 = array([2,4,5,6,7])
arr2 = arr1.view()
arr1[1] = 9
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 9 5 6 7]
[2 9 5 6 7]
1568385562448
1568385559472


#### Working with Matrix in Python

In [113]:
from numpy import *
arr1 = array([
    [1,9,7],
    [2,5,7]
])
print(arr1)

[[1 9 7]
 [2 5 7]]


In [115]:
from numpy import *
arr1 = array([
    [1,9,7],
    [2,5,7]
])
print(arr1.shape)

(2, 3)


In [117]:
from numpy import *
arr1 = array([
    [1,9,7],
    [2,5,7]
])
print(arr1.dtype)

int32


In [119]:
from numpy import *
arr1 = array([
    [1,9,7],
    [2,5,7]
])
print(arr1.ndim)

2


In [121]:
from numpy import *
arr1 = array([
    [1,9,7],
    [2,5,7]
])
print(arr1.shape)

(2, 3)


In [123]:
from numpy import *
arr1 = array([
    [1,9,7],
    [2,5,7]
])
print(arr1.size)

6


In [137]:
from numpy import *
arr1 = array([
    [1,2,3,6,2,9],
    [4,5,6,7,5,3]
])
arr2 = arr1.flatten()
arr3 = arr2.reshape(2,2,3)

print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [149]:
from numpy import *
arr1 = array([
    [1,2,3,6],
    [4,5,6,7]
])
m = matrix(arr1)



print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [151]:
from numpy import *
arr1 = array([
    [1,2,3,6],
    [4,5,6,7]
])
m = matrix('1 2 3 6 ; 4 5 6 7')



print(arr3)

[[[1 2 3]
  [6 2 9]]

 [[4 5 6]
  [7 5 3]]]


In [161]:
from numpy import *
 
m = matrix('1 2 3; 6 4 5; 1 6 7')
print(m)

[[1 2 3]
 [6 4 5]
 [1 6 7]]


In [163]:
from numpy import *
 
m = matrix('1 2 3; 6 4 5; 1 6 7')
print(diagonal(m))

[1 4 7]


In [165]:
from numpy import *
 
m = matrix('1 2 3; 6 4 5; 1 6 7')
print(m.min())

1


In [169]:
from numpy import *
 
m = matrix('1 2 3; 6 4 5; 1 6 7')
print(m.max())

7


In [173]:
from numpy import *
 
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('9 5 3; 1 6 5; 2 4 7')

m3 = m1 + m2;
print(m3)

[[10  7  6]
 [ 7 10 10]
 [ 3 10 14]]


In [175]:
from numpy import *
 
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('9 5 3; 1 6 5; 2 4 7')

m3 = m1 * m2;
print(m3)

[[17 29 34]
 [68 74 73]
 [29 69 82]]
